[package]
name    = "domain"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[lib]
name = "domain"
path = "src/lib.rs"

#[[example]]
#name = "dig"
#path = "examples/dig.rs"

#[[example]]
#name = "host"
#path = "examples/host.rs"

#[[example]]
#name = "rusthome"
#path = "examples/rusthome.rs"

[dependencies]
byteorder   = "0.5"
rand        = "0.3"
futures     = "0.1"
tokio-core  = "0.1"

[dev-dependencies]
argparse     = "0.2"
tokio-tls    = { git = "https://github.com/tokio-rs/tokio-tls" }
