[package]
name = "domain"
version = "0.2.5"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
description = "A DNS library for Rust."
documentation = "https://docs.rs/domain/"
homepage = "https://github.com/partim/domain"
repository = "https://github.com/partim/domain"
readme = "README.md"
keywords = ["DNS", "domain", "resolver", "futures"]
license = "MIT"

[lib]
name = "domain"
path = "src/lib.rs"

[dependencies]
byteorder     = "1.2"
rand          = "0.4"
futures       = "0.1.18"
tokio-core    = "0.1.12"

[dev-dependencies]
argparse     = "0.2"
native-tls   = "0.1.5"
tokio-io     = "0.1.5"
tokio-tls    = "0.1.4"

